version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Start docker services for rpmbuild
          command: docker-compose -f rpmbuild/docker-compose.yml up -d
      - run:
          name: Check running services
          command: docker ps
