version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:201711-01
    steps:
      - run:
          name: Upgrade Docker CE
          command: |
            sudo apt-get update
            #sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
            #curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            #sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            #sudo apt-get update
            sudo apt-get install docker-ce
      - run:
          name: Upgrade Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Checkout code
          environment:
            CIRCLE_REPOSITORY_URL: https://github.com/aursu/rpmbuild-php-5.6.git
          command: |
            if [ -e /home/circleci/project ]
            then
              rm -rf /home/circleci/project
            fi
            mkdir -p /home/circleci/project
            cd /home/circleci/project
            git clone --recursive "$CIRCLE_REPOSITORY_URL" .
            
            if [ -n "$CIRCLE_TAG" ]
            then
              git fetch --force origin "refs/tags/${CIRCLE_TAG}"
            else
              git fetch --force origin "master:remotes/origin/master"
            fi
            if [ -n "$CIRCLE_TAG" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q "$CIRCLE_TAG"
            elif [ -n "$CIRCLE_BRANCH" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q -B "$CIRCLE_BRANCH"
            fi
            
            git reset --hard "$CIRCLE_SHA1"
      - run:
          name: Start docker services for rpmbuild
          command: docker-compose -f rpmbuild/docker-compose.yml up -d
      - run:
          name: Check running services
          command: docker ps
