version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Checking Docker engine version
          command: docker version
      - run:
          name: Check Docker Compose version
          command: docker-compose version
