version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Install Docker
          command: echo install docker
      - run:
          name: Install Docker Compose
          command: echo install docker-compose
