version: "3.5"
services:
  centos7php5run:
    build:
      context: .
    image: aursu/php5build:7-runtime
  centos7php5devbase:
    build:
      context: .
      args:
        image: 7-nodedev
    image: aursu/php5build:7-devbase
